config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  resources :recruitments
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  devise_scope :user do
    get 'profile_edit', to: 'users/registrations#profile_edit', as: 'profile_edit'
    patch 'profile_update', to: 'users/registrations#profile_update', as: 'profile_update'
  end

  root "recruitments#index"
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability
  def initialize(user)
    if user.try(:admin?)
      can :access, :rails_admin
      can :manage, :all
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/recruitment.rb
class Recruitment < ApplicationRecord
    belongs_to :user
    validates :play_now, presence: true
    validates :game_title, presence: true
    validates :comment, presence: true
    validates :machine, presence: true
    validates :image, presence: true
    validates :on_off, presence: true
    validates :purpouse, presence: true
    validates :comment,    length: { in: 1..250 }
    validates :game_title,    length: { in: 1..30 }

    enum play_now: { 今遊ぶ: 0, 定期的に: 1, あとで: 2, いつか: 3 }
    enum machine: { PC: 0, スマホ: 1, swhich: 2, PS4: 3, PSVITA: 4, PS5: 5, カードゲーム: 6, xboxone: 7, その他: 8 }
    enum on_off: { オンライン: 0, オフライン: 1 }
    enum purpouse: { フレンド: 0, 協力プレイ: 1, 対戦: 2, 練習: 3, 経験値稼ぎ: 4, イベント周回: 5, イベント参加: 6, 大会: 7, 楽しくお話: 8, その他の目的: 9 }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :recruitments
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/recruitments_controller.rb
class RecruitmentsController < ApplicationController
    before_action :set_recruitment, only: [:show, :edit, :update, :destroy]
    before_action :authenticate_user!, only: [:edit, :update, :destroy]
      def index
        @recruitments = Recruitment.all
        @recruitment = Recruitment.new
      end
      def create
        @recruitment = Recruitment.new(recruitment_params)
        if @recruitment.save
          redirect_to recruitments_path, notice: "募集を作成しました！"
        else
          render :edit
        end
      end
      def show
      end
      def edit
      end
      def update
        if @recruitment.update(recruitment_params)
          redirect_to recruitments_path, notice: "募集を編集しました！"
        else
          render :edit
        end
      end
      def destroy
        @recruitment.destroy
        redirect_to recruitments_path, notice:"募集を削除しました！"
      end
      private
      def recruitment_params
        params.require(:recruitment).permit(:play_now, :game_title, :comment, :machine, :image, :on_off, :purpouse )
      end
      # idをキーとして値を取得するメソッドを追加
      def set_recruitment
        @recruitment = Recruitment.find(params[:id])
      end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recruitments_helper.rb
module RecruitmentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SampleApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if user_signed_in? %>
      <%= link_to "募集の作成", recruitments_path %>
      <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to "新規登録", new_user_registration_path %>
      <%= link_to "ログイン", new_user_session_path %>
    <% end %>

    <% if notice %>
      <p class="alert alert-notice"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-error"><%= alert %></p>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/recruitments/_form.html.erb
<%= form_with(model: @recruitment, local: true) do |form| %>
    <% if @recruitment.errors.any? %>
    <div id="error_explanation">
      <h2><%= @recruitment.errors.count %>件のエラーがあります。</h2>
      <p>作成し直してください</p>
      <ul>
      <% @recruitment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
    <% end %>
    <%= form.label :今遊びますか？ %>
    <%= form.select :play_now, ['今遊ぶ', '定期的に', 'あとで', 'いつか'] %>

    <%= form.label :ゲームタイトル %>
    <%= form.text_field :game_title %>

    <%= form.label :コメント %>
    <%= form.text_field :comment %>

    <%= form.label :機種 %>
    <%= form.select :machine, ['PC', 'スマホ', 'swhich','PS4', 'PSVITA', 'PS5','カードゲーム', 'xboxone', 'その他'] %>

    <%= form.label :写真 %>
    <%= form.text_field :image %>

    <%= form.label :オフライン？オンライン？ %>
    <%= form.select :on_off, ['オンライン', 'オフライン'] %>

    <%= form.label :目的 %>
    <%= form.select :purpouse, ['フレンド', '協力プレイ', '対戦','練習', '経験値稼ぎ', 'イベント周回', 'イベント参加', '大会', '楽しくお話', 'その他目的'] %>

    <%= form.submit %>
<% end %>

app/views/recruitments/edit.html.erb
<h2>作成画面</h2>
<%= render 'form' %>

app/views/recruitments/index.html.erb
<% if current_user.try(:admin?) %>
  <h1>募集一覧_admin</h1>
<% else %>
  <h1>募集一覧</h1>
<% end %>
<p><%= notice %></p>
<h2>募集を作成する</h2>
<%= render 'form' %>
<table>
  <tr>
    <th>今遊ぶ？</th>
    <th>ゲームタイトル</th>
    <th>コメント</th>
    <th>機種</th>
    <th>画像</th>
    <th>オンライン？オフライン？</th>
    <th>目的</th>

  </tr>
<% @recruitments.each do |recruitment| %>
  <tr>
    <td><%= recruitment.play_now %></td>
    <td><%= recruitment.game_title %></td>
    <td><%= recruitment.comment %></td>
    <td><%= recruitment.machine %></td>
    <td><%= recruitment.image %></td>
    <td><%= recruitment.on_off %></td>
    <td><%= recruitment.purpouse %></td>
    <td><%= link_to '詳細を確認する', recruitment_path(recruitment.id) %></td>
  </tr>
<% end %>
</table>
<br>

app/views/recruitments/show.html.erb
<h1>募集詳細画面</h1>
<table>
    <tr>
        <th>今遊ぶ？</th>
        <th>ゲームタイトル</th>
        <th>コメント</th>
        <th>機種</th>
        <th>画像</th>
        <th>オンライン？オフライン？</th>
        <th>目的</th>
    </tr>
    <tr>
        <td><%= @recruitment.play_now %></td>
        <td><%= @recruitment.game_title %></td>
        <td><%= @recruitment.comment %></td>
        <td><%= @recruitment.machine %></td>
        <td><%= @recruitment.image %></td>
        <td><%= @recruitment.on_off %></td>
        <td><%= @recruitment.purpouse %></td>
    </tr>
</table>
<%= link_to "編集する", edit_recruitment_path(@recruitment.id) %>
<%= link_to '募集を削除する', recruitment_path(@recruitment.id), method: :delete ,data: { confirm: '本当に削除していいですか？' } %>
<p>
<%= link_to '募集一覧へ', recruitments_path %>
</p>